# Generated by Django 4.1.2 on 2024-07-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('semina', models.CharField(choices=[('1', 'Tushlikgacha'), ('2', "Tushlikdan so'ng")], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('is_group', models.BooleanField(blank=True, default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('sciences', models.ManyToManyField(related_name='teachers', to='TimeTable.science')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_per_week', models.PositiveIntegerField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.classroom')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.science')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.teacher')),
            ],
            options={
                'unique_together': {('classroom', 'science')},
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='sciences',
            field=models.ManyToManyField(related_name='classes', through='TimeTable.ClassRoomScience', to='TimeTable.science'),
        ),
    ]
