# Generated by Django 4.1.2 on 2024-06-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='science',
            field=models.ManyToManyField(related_name='teacher', to='TimeTable.science'),
        ),
    ]
