# Generated by Django 4.1.2 on 2024-07-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='sciences',
        ),
    ]
