# Generated by Django 4.1.2 on 2024-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0002_remove_classroom_sciences'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
