# Generated by Django 4.1.2 on 2024-06-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0003_alter_science_description_alter_teacher_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('semina', models.CharField(choices=[('1', 'Tushlikgacha'), ('2', "Tushlikdan so'ng")], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=55)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='science',
        ),
        migrations.AddField(
            model_name='teacher',
            name='sciences',
            field=models.ManyToManyField(related_name='teachers', to='TimeTable.science'),
        ),
        migrations.CreateModel(
            name='ClassRoomScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_per_week', models.PositiveIntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.classroom')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.science')),
            ],
            options={
                'unique_together': {('classroom', 'science')},
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='sciences',
            field=models.ManyToManyField(related_name='classes', through='TimeTable.ClassRoomScience', to='TimeTable.science'),
        ),
    ]
