# Generated by Django 4.1.2 on 2024-06-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0004_classroom_remove_teacher_science_teacher_sciences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='number',
        ),
    ]
