# Generated by Django 4.1.2 on 2024-07-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0004_remove_teacher_day_teacher_workdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='workdays',
        ),
        migrations.AddField(
            model_name='teacher',
            name='workdays',
            field=models.ManyToManyField(related_name='teachers', to='TimeTable.worksday'),
        ),
    ]
