# Generated by Django 4.1.2 on 2024-07-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0005_worksday_remove_teacher_workdays_teacher_workdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksday',
            name='day',
        ),
    ]
