# Generated by Django 4.1.2 on 2024-07-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0006_remove_worksday_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='workdays',
        ),
        migrations.DeleteModel(
            name='WorksDay',
        ),
        migrations.AddField(
            model_name='teacher',
            name='workdays',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
