# Generated by Django 4.1.2 on 2024-07-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0007_remove_teacher_workdays_delete_worksday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='workdays',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=255),
        ),
    ]
