# Generated by Django 4.1.2 on 2024-07-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0008_alter_teacher_workdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='workdays',
            field=models.CharField(max_length=255),
        ),
    ]
