# Generated by Django 4.1.2 on 2024-08-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0010_classroomscience_teacher2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=45, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='semina',
            field=models.CharField(choices=[('1', 'Tushlikgacha'), ('2', "Tushlikdan so'ng")], max_length=50, verbose_name='semina'),
        ),
        migrations.AlterField(
            model_name='classroomscience',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.classroom', verbose_name='classroom'),
        ),
        migrations.AlterField(
            model_name='classroomscience',
            name='science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.science', verbose_name='science'),
        ),
        migrations.AlterField(
            model_name='classroomscience',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeTable.teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='classroomscience',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher2', to='TimeTable.teacher', verbose_name='teacher2'),
        ),
        migrations.AlterField(
            model_name='classroomscience',
            name='times_per_week',
            field=models.PositiveIntegerField(verbose_name='times_per_week'),
        ),
        migrations.AlterField(
            model_name='science',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='science',
            name='is_group',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_group'),
        ),
        migrations.AlterField(
            model_name='science',
            name='name',
            field=models.CharField(max_length=45, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fullname',
            field=models.CharField(max_length=60, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sciences',
            field=models.ManyToManyField(related_name='teachers', to='TimeTable.science', verbose_name='sciences'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='workdays',
            field=models.CharField(max_length=255, verbose_name='workdays'),
        ),
    ]
